# -*- coding: utf-8 -*-
"""pp_lab.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PQObSYtYF19YaXihuagyg1BnT436LsOl
"""

l=[3,5,4,5,'list']
print(l)
l.insert(0,[1,2])
print(l)
l.append(2)
l.remove(5)
print(l)
m=len(l)
print(m)
m=l.pop(1)
print(m)
print(l)
del l[2]
print(l)
l1=[1,2,3,4,]
l.extend(l1)
print(l)

d={1:'one',2:'two',3:'four'}
print(d)
print(d.items())
print(d.keys())
print(d.values())
print(d.get(2))
d1={3:'three'}
d.update(d1)
print(d)
print(3 in d)
m=len(d)
print(m)
m=d.pop(1)
print(m)
del (d[2])
print(d)
d

t=4,5,6
print(t)
t+=1,2,3
print(t)
print(len(t))
print(3 in t)
print(t[3])
print(t.count(3))
m=t.index(4)
print(m)

a=int(input('enter the a value:'))
b=int(input('enter the b value:'))
c=a+b
print(c)

n=int(input("eneter a number"))
if n>0:
  print("positive number")
else:
  print("negative numbeo")

a=int(input('enter the value of a:'))
b=int(input('enter the value of b:'))
c=int(input('enter the value of c:'))
if a>b:
  if a>c:
    print('a is greatest value')
else:
  print('c is greatest value')

a=int(input("enter the number:"))
if a>0:
    print("given number is positive")
elif a<0:
    print("given number is negative")
else:
    print("given number is zero")

a=int(input("Enter the value of a:"))
b=int(input("Enter the value of b:"))
c=int(input("Enter the value of c:"))
if a>b and a>c:
    print("a is greater")
elif b>c and b>a:
    print("b is greater")
else:
    print("c is greater")

day=int(input("Enter a number(1-7):"))
if day==1:
    print("\n Monday")
elif day==2:
    print("\n Tuesday")
elif day==3:
    print("\n Wednesday")
elif day==4:
    print("\n Thursday")
elif day==5:
    print("\n Friday")
elif day==6:
    print("\n Saturday")
elif day==7:
    print("\n Sunday")
else:
    print("Please enter the correct number!")

num1 =eval(input("Enter the first number:"))
num2 =eval(input("Enter the second number:"))
 
def perform(num1,num2):
    while 1:
        print("**********")
        print("1.To perform addition")
        print("2.To perform subtraction")
        print("3.To perform multiplication")
        print("4.To perform division")
        print("5.To exit")
        ch=int(input())
        if ch==1:
            c=num1+num2
            print("Addition of",num1,"and",num2,"is:",c)
        elif ch==2:
            c=num1-num2
            print("Subtraction of",num1,"and",num2,"is:",c)
        elif ch==3:
            c=num1*num2
            print("Multiplication of",num1,"and",num2,"is:",c)
        elif ch==4:
            c=num1/num2
            print("division of",num1,"and",num2,"is:",c)
        elif ch==5:
            exit()
        else:
            print("Enter a number from the menu!")
 
perform(num1,num2)

string=input(("Enter the string:"))  
if(string==string[::-1]):  
      print("The entered string is palindrome")  
else:  
      print("The entered string is not palindrome")

def factorial(num):
    fact = 1
 
    for i in range(1, num + 1):
        fact = fact * i
 
    return fact
 
number=int(input(" Please enter any Number to find factorial :"))
 
factof= factorial(number)
print("The factorial of %d  = %d" %(number, factof))

def check(list_1, list_2):
    if len(list_1) != len(list_2):
        return False
    else:
        return sorted(list_1) == sorted(list_2)
list_1=[]
list_2=[]
n1=int(input("Enter number of elements in list_1:"))
n2=int(input("Enter number of elements in list_2:"))
    
for i in range(0,n1):
    ele=input()
    list_1.append(ele)
print(list_1)
for i in range(0,n2):￼

    elem=input()
    list_2.append(elem)
print(list_2)
if check(list_1,list_2):
    print("Two lists are equal")
else:
    print("Lists are not equal")

todouble=lambda x:2*x
print((todouble(5)))
 
#to add two numbers
toadd=lambda x,y:x+y
print(toadd(10,4))

list_1=[]
n=int(input("Enter the size:"))
for i in range(0,n):￼

    ele=int(input())
    list_1.append(ele)
newList=list(filter(lambda x:x%2==0,list_1))
print(newList)

list_1=[]
n=int(input("Enter the size:"))
for i in range(0,n):
    ele=int(input())
    list_1.append(ele)
newList=list(map(lambda x:x*2,list_1))
print(newList)

import functools
list_1=[]
n=int(input("Enter the size:"))
for i in range(0,n):
    ele=int(input())/
    list_1.append(ele)
print(functools.reduce(lambda x,y:x+y,list_1))

tuple1=((3,4,6),(1,2,3,5),(6,5,2,1,8,16),(4,3))
def count_digit(e):
  return len(e)
list1=list(tuple1)
print(list1)
list1.sort(key=count_digit)
tuple1=tuple(list1)
print("sorted tuple is:",tuple1)

emp=((200,'vitika',90000),(20,'sita',50000),(40,'karthik',20000))
print(sorted(emp))
print(sorted(emp,key=lambda x:x[1]))

tuple1=((1,'rani',20),(2,'ravi',21),(3,'geeta',22),(4,'raju',23))
print(tuple1)
newtuple=[{'key':sub[0],'value':sub[1],'id':sub[2]} for sub in tuple1]
print("the converted dictionary is:",newtuple)

tuple1=(('ram',7),('raju',5),('rani',8),('vani',9))
print(tuple1)
list1=list(tuple1)
def sortlist(list1):
  list1.sort(key=lambda x:x[1])
  return list1
tuple1=tuple(sortlist(list1))
print(tuple1)

dict1={'name':'sai','age':20}
dict2={'name':'sai','age':20}
if dict1==dict2:
  print("dict1 is equal to dict2")
else:
  print("dict1 is not equal to dict2")

dict1={'apple':33,'mango':22,'grape':25}
s=0
for val in dict1.values():


  s=s+val
s=s/len(dict1)
print("average of dictionary values=",s)

dict1={'abc':5,'def':7,'ghi':3}
print(dict1)
k=5
res={}
for key in dict1:
  if not(isinstance(dict1[key],int) and dict1[key]>k):
    res[key]=dict1[key]
print("the constructed dictionary=",str(res))



